import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import { ArticleDetailResponse, ArticleDetail } from '@/types/articleDatailDTO';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { getArticleDetail } from '../../api/getArticleDetail';

const ArticlePage: React.FC = () => {
  const router = useRouter();
  const [articleDetail, setArticleDetail] = useState<ArticleDetailResponse>();
  useEffect(() => {
    const fetchData = async () => {
      const slug = router.query.slug;
      if (slug == undefined) {
        return;
      }
      const data = await getArticleDetail(slug as String);

      setArticleDetail(data);
    };
    fetchData();
  }, []);

  return (
    <>
      <div id="ng-scope">
        <Head>
          <link rel="stylesheet" href="//demo.productionready.io/main.css" />
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        {/* <ArticlePage /> */}
        <Footer />
      </div>
      <div className="article-page">
        <div className="banner">
          <div className="container">
            <h1>{articleDetail?.article.title}</h1>
            <div className="article-meta">
              <a href="/">
                <img
                  src={articleDetail?.article.author.image}
                  alt="Author Image"
                />
              </a>
              <div className="info">
                <a href="" className="author">
                  {articleDetail?.article.author.username}
                </a>
                <span className="date">{articleDetail?.article.createdAt}</span>
              </div>
              <button className="btn btn-sm btn-outline-secondary">
                <i className="ion-plus-round"></i>
                &nbsp; Follow {articleDetail?.article.author.username}{' '}
                <span className="counter">(10)</span>
              </button>
              &nbsp;&nbsp;
              <button className="btn btn-sm btn-outline-primary">
                <i className="ion-heart"></i>
                &nbsp; Favorite Post{' '}
                <span className="counter">
                  {articleDetail?.article.favoritesCount}
                </span>
              </button>
            </div>
          </div>
        </div>

        <div className="container page">
          <div className="row article-content">
            <div className="col-md-12">
              <p>{articleDetail?.article.body}</p>
            </div>
          </div>

          <hr />

          <div className="article-actions">
            <div className="article-meta">
              <a href="/">
                <img
                  src={articleDetail?.article.author.image}
                  alt="Author Image"
                />
              </a>
              <div className="info">
                <a href="" className="author">
                  {articleDetail?.article.author.username}
                </a>
                <span className="date">January 20th</span>
              </div>
              <button className="btn btn-sm btn-outline-secondary">
                <i className="ion-plus-round"></i>
                &nbsp; Follow {articleDetail?.article.author.username}
              </button>
              &nbsp;
              <button className="btn btn-sm btn-outline-primary">
                <i className="ion-heart"></i>
                &nbsp; Favorite Article{' '}
                <span className="counter">
                  {articleDetail?.article.favoritesCount}
                </span>
              </button>
            </div>
          </div>

          <div className="row">
            <div className="col-xs-12 col-md-8 offset-md-2">
              <form className="card comment-form">
                <div className="card-block">
                  <textarea
                    className="form-control"
                    placeholder="Write a comment..."
                    rows={3}
                  ></textarea>
                </div>
                <div className="card-footer">
                  <img
                    src="http://i.imgur.com/Qr71crq.jpg"
                    alt="Author Image"
                    className="comment-author-img"
                  />
                  <button className="btn btn-sm btn-primary">
                    Post Comment
                  </button>
                </div>
              </form>

              <div className="card">
                <div className="card-block">
                  <p className="card-text">
                    With supporting text below as a natural lead-in to
                    additional content.
                  </p>
                </div>
                <div className="card-footer">
                  <a href="/" className="comment-author">
                    <img
                      src="http://i.imgur.com/Qr71crq.jpg"
                      alt="Author Image"
                      className="comment-author-img"
                    />
                  </a>
                  &nbsp;
                  <a href="/" className="comment-author">
                    Jacob Schmidt
                  </a>
                  <span className="date-posted">Dec 29th</span>
                </div>
              </div>

              <div className="card">
                <div className="card-block">
                  <p className="card-text">
                    With supporting text below as a natural lead-in to
                    additional content.
                  </p>
                </div>
                <div className="card-footer">
                  <a href="/" className="comment-author">
                    <img
                      src="http://i.imgur.com/Qr71crq.jpg"
                      alt="Author Image"
                      className="comment-author-img"
                    />
                  </a>
                  &nbsp;
                  <a href="/" className="comment-author">
                    Jacob Schmidt
                  </a>
                  <span className="date-posted">Dec 29th</span>
                  <span className="mod-options">
                    <i className="ion-edit"></i>
                    <i className="ion-trash-a"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ArticlePage;
